### ISSUE TITLE
relations / edges not always rendered

### ISSUE THREAD

**Issue by rpietzsch** [metaphacts/ontodia#192]
I recognized that relations / edged are not always rendered, esp. with a higher number of nodes. is this configurable if so where? or a known limitation/bug? thanks.

**Comment by AlexeyMz** [comment]
Hi, @rpietzsch 

I'm not sure but I think what you are observing is Ontodia trying to execute too large/heavy query for edges between visible nodes on a diagram.

If that's the case you may try to work around this limitation in some use-cases by querying the whole graph with e.g. CONSTRUCT query, placing it in `RdfDataProvider` and use it instead. See  RDF data provider example here: https://github.com/metaphacts/ontodia/blob/master/src/examples/rdf.ts

**Comment by rpietzsch** [comment]
Hi @AlexeyMz thanks for this hint. Will give this a try and consider this as done for now.
